# Generated by Django 5.2.2 on 2026-07-04 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                (
                    "field_name",
                    models.CharField(db_index=True, default="status", max_length=64),
                ),
                ("from_state", models.CharField(blank=True, max_length=64, null=True)),
                ("to_state", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="audit_ent_lookup_idx"
                    ),
                    models.Index(
                        fields=["field_name", "occurred_at"],
                        name="audit_field_time_idx",
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"], name="audit_actor_time_idx"
                    ),
                ],
            },
        ),
    ]
