# Generated by Django 5.2.2 on 2026-07-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=32)),
                ("bank", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("current", "Current"),
                            ("wallet", "Wallet"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("dismissed", "Dismissed"),
                            ("unlinked", "Unlinked"),
                        ],
                        db_index=True,
                        default="unlinked",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="disc_acc_user_status_idx"
                    ),
                    models.Index(
                        fields=["bank", "account_number"], name="disc_acc_bank_acct_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_number", "bank", "account_type"),
                        name="discovered_account_unique_per_user",
                    )
                ],
            },
        ),
    ]
