# Generated by Django 5.2.2 on 2026-07-07 15:36

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_discoveredaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="raw_email_reference_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("gmail", "Gmail")],
                db_index=True,
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discoveredaccount",
            name="first_seen_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoveredaccount",
            name="supporting_email_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("raw_email_reference_id", ""), ("source", "gmail"), _connector="OR"
                ),
                name="bank_tx_raw_ref_requires_gmail_source",
            ),
        ),
    ]
