# Generated by Django 5.2.2 on 2026-07-04 07:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("disbursed", "Disbursed"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "repayment_term_months",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField()),
                ("purpose", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrowed_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funded_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="loan_status_idx"),
                    models.Index(
                        fields=["borrower", "status"], name="loan_borrower_status_idx"
                    ),
                    models.Index(
                        fields=["lender", "status"], name="loan_lender_status_idx"
                    ),
                    models.Index(fields=["created_at"], name="loan_created_at_idx"),
                    models.Index(
                        fields=["starts_at", "ends_at"], name="loan_period_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("principal_amount__gt", 0)),
                        name="loan_principal_amount_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("interest_rate__gte", 0), ("interest_rate__lte", 100)
                        ),
                        name="loan_interest_rate_between_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("repayment_term_months__gte", 1)),
                        name="loan_repayment_term_months_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="loan_ends_at_after_starts_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lender__isnull", True),
                            models.Q(("borrower", models.F("lender")), _negated=True),
                            _connector="OR",
                        ),
                        name="loan_lender_not_borrower",
                    ),
                ],
            },
        ),
    ]
