# Generated by Django 5.2.2 on 2026-07-04 08:42

import apps.loans.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField(db_index=True)),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[apps.loans.validators.validate_positive_amount],
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[apps.loans.validators.validate_non_negative_amount],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["loan_id", "installment_number"],
                "indexes": [
                    models.Index(
                        fields=["loan", "status"], name="repayment_loan_status_idx"
                    ),
                    models.Index(
                        fields=["loan", "due_date"], name="repayment_loan_due_date_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("loan", "installment_number"),
                        name="repayment_unique_installment_per_loan",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_due__gt", 0)),
                        name="repayment_amount_due_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_paid__gte", 0)),
                        name="repayment_amount_paid_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_paid__lte", models.F("amount_due"))
                        ),
                        name="repayment_amount_paid_lte_amount_due",
                    ),
                ],
            },
        ),
    ]
