# Generated by Django 5.2.2 on 2026-07-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_repayment"),
        ("payments", "0002_discoveredaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="repayment",
            name="match_confidence",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="repayment",
            name="matched_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_repayments",
                to="payments.banktransaction",
            ),
        ),
        migrations.AddField(
            model_name="repayment",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repayment",
            name="requires_manual_review",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="repayment",
            name="transaction_reference",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_invite", "Pending Invite"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("disbursed", "Disbursed"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
    ]
