# Generated by Django 5.2.2 on 2026-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_repayment_match_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="source_transaction_reference",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
