# Generated by Django 5.2.2 on 2026-07-04 09:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_ledger_actor_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="family.family",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_ledger_member_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="family.family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["family_id", "joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="family",
            index=models.Index(fields=["owner"], name="family_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="family",
            index=models.Index(fields=["created_at"], name="family_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="familyledgerentry",
            index=models.Index(
                fields=["family", "created_at"], name="fam_ledger_family_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familyledgerentry",
            index=models.Index(fields=["action"], name="family_ledger_action_idx"),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(
                fields=["family", "role"], name="family_member_family_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familymember",
            index=models.Index(fields=["user"], name="family_member_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.UniqueConstraint(
                fields=("family", "user"), name="family_member_unique_per_family"
            ),
        ),
    ]
