# Generated by Django 5.2.2 on 2026-07-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailSyncedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_message_id", models.CharField(max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("snippet", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_at", "-synced_at"],
            },
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="token_scopes",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="gmailaccount",
            index=models.Index(
                fields=["user", "is_primary"], name="gmail_account_user_primary_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailaccount",
            index=models.Index(
                fields=["gmail_address"], name="gmail_account_address_idx"
            ),
        ),
        migrations.AddField(
            model_name="gmailsyncedemail",
            name="gmail_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synced_emails",
                to="accounts.gmailaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="gmailsyncedemail",
            index=models.Index(
                fields=["gmail_account", "received_at"], name="gmail_email_acc_recv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailsyncedemail",
            index=models.Index(
                fields=["gmail_message_id"], name="gmail_email_message_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gmailsyncedemail",
            constraint=models.UniqueConstraint(
                fields=("gmail_account", "gmail_message_id"),
                name="gmail_synced_email_unique_per_account",
            ),
        ),
    ]
